import { useEffect } from "react";
import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import {
  FileText,
  Search,
  Trash2,
  Clock,
  Zap,
  Shield,
  Activity,
  MessageSquare,
  ArrowRight,
  TrendingUp,
} from "lucide-react";
import { useDocumentStore } from "@/store/documentStore";
import { Sidebar } from "@/components/Sidebar";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

export default function History() {
  const { recentActivity, isLoading, fetchAllHistory } = useDocumentStore();

  useEffect(() => {
    fetchAllHistory();
  }, [fetchAllHistory]);

  const getOperationIcon = (type: string) => {
    switch (type) {
      case "simplify": return <Zap className="w-5 h-5 text-purple-400" />;
      case "summarize": return <TrendingUp className="w-5 h-5 text-indigo-400" />;
      case "analyze-risk": return <Shield className="w-5 h-5 text-orange-400" />;
      case "chat": return <MessageSquare className="w-5 h-5 text-blue-400" />;
      case "compare": return <Activity className="w-5 h-5 text-pink-400" />;
      default: return <FileText className="w-5 h-5 text-slate-400" />;
    }
  };

  return (
    <div className="min-h-screen md:ml-64 relative z-0">
      <Sidebar />
      <div className="p-6 md:p-8 max-w-6xl mx-auto relative z-10">
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-10"
        >
          <h1 className="text-4xl font-extrabold text-white mb-2">Analysis History</h1>
          <p className="text-slate-400 text-lg">Tracks every AI insight and decision generated by LegalSenser</p>
        </motion.div>

        {isLoading ? (
          <div className="flex flex-col items-center justify-center py-32 gap-4">
             <div className="w-16 h-16 border-4 border-blue-500/20 border-t-blue-500 rounded-full animate-spin" />
             <p className="text-slate-500 font-bold uppercase tracking-widest text-xs">Retrieving audit trails...</p>
          </div>
        ) : recentActivity && recentActivity.length > 0 ? (
          <div className="space-y-4">
            {recentActivity.map((item, index) => (
              <motion.div
                key={item._id || index}
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: index * 0.05 }}
              >
                <Card className="bg-slate-900/50 border-white/5 hover:border-blue-500/30 transition-all group overflow-hidden">
                  <CardContent className="p-6">
                    <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">
                      <div className="flex items-start gap-5">
                        <div className="p-4 bg-slate-800 rounded-2xl group-hover:scale-110 transition-transform duration-300">
                          {getOperationIcon(item.operationType)}
                        </div>
                        <div>
                          <div className="flex items-center gap-3 mb-1">
                            <h3 className="text-xl font-bold text-white group-hover:text-blue-400 transition-colors uppercase tracking-tight">
                              {item.title || "AI Operation"}
                            </h3>
                            <Badge className="bg-slate-800 text-slate-400 border-white/10 uppercase text-[10px] py-0">
                              {item.operationType}
                            </Badge>
                          </div>
                          <p className="text-slate-500 text-sm flex items-center gap-2">
                             <Clock className="w-3 h-3" />
                             {new Date(item.createdAt).toLocaleString()}
                          </p>
                          {item.document?.title && (
                            <p className="text-blue-400/60 text-xs font-bold mt-1 flex items-center gap-1">
                              <FileText className="w-3 h-3" />
                              Linked to: {item.document.title}
                            </p>
                          )}
                        </div>
                      </div>

                      <div className="flex items-center gap-3">
                        <Link to={item.document?._id ? `/document/${item.document._id}` : "#"}>
                          <Button variant="outline" className="bg-white/5 border-white/10 hover:bg-white/10 text-white rounded-xl gap-2">
                            View Report
                            <ArrowRight className="w-4 h-4" />
                          </Button>
                        </Link>
                        <Button variant="ghost" size="icon" className="text-slate-500 hover:text-red-400 hover:bg-red-500/10 rounded-full">
                          <Trash2 className="w-4 h-4" />
                        </Button>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              </motion.div>
            ))}
          </div>
        ) : (
          <div className="text-center py-24 bg-slate-900/30 border border-dashed border-white/5 rounded-3xl">
             <Activity className="w-16 h-16 text-slate-700 mx-auto mb-6" />
             <h3 className="text-2xl font-bold text-white mb-2">No history records</h3>
             <p className="text-slate-500 max-w-sm mx-auto mb-8">
               Your analysis journey hasn't started yet. Upload a document to generate your first AI report.
             </p>
             <Link to="/upload">
               <Button className="bg-gradient-to-r from-blue-600 to-purple-600 px-8 h-12 rounded-full font-bold">
                 Get Started
               </Button>
             </Link>
          </div>
        )}
      </div>
    </div>
  );
}
